### ISSUE TITLE
Change Tab Titles Color

### ISSUE THREAD

**Issue by marco2012** [florent37/MaterialViewPager#323]
How can I change the color of Tab titles? 
They're black, but I'd like them white as in[ this video ](https://www.youtube.com/watch?v=g6tTDVceM9E&feature=youtu.be)

**Comment by lovelyYakir** [comment]
the same , i can't find a right to change the color or tab,it always black

**Comment by Breaking** [comment]
in styles.xml add this line:
<item name="android:textColorPrimary">@android:color/white</item>

**Comment by marco2012** [comment]
Thanks!

**Comment by zboing** [comment]
This is not a good approach because the color of the settings and popup overflow menu items will be white color text to white elements (not visible to the user).
A proper use case will be to leave the option from styles.xml unchanged
`<item name="android:textColorPrimary">@android:color/black</item>`
and add the line
`    app:pstsTabTextColor="@android:color/white"`
to com.astuetz.PagerSlidingTabStrip component from material_view_pager_pagertitlestrip_newstand.xml
