### ISSUE TITLE
First item of recycler view is above tabs and toolbar

### ISSUE THREAD

**Issue by TheLester** [florent37/MaterialViewPager#33]
![screenshot_2015-05-25-11-46-03](https://cloud.githubusercontent.com/assets/6323430/7794517/16740c56-02d4-11e5-8f96-d587912453c1.png)

or sometimes its below them:
![screenshot_2015-05-25-11-55-27](https://cloud.githubusercontent.com/assets/6323430/7794655/5e94800a-02d5-11e5-9517-8ac60233a98d.png)

I have this line  MaterialViewPagerHelper.registerRecyclerView(getActivity(), betsRecycler, null); on OnCreateView of Fragment
MaterialViewPager layout from sample/  Recycler :
<android.support.v7.widget.RecyclerView
    android:id="@+id/bets_list"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"/>

**Comment by omidheshmatinia** [comment]
i guess the problem is in your fragment
"mAdapter=new RecyclerViewMaterialAdapter(new RecyclerNewsListAdapter(mActivity,allNews));"
you forget this part "new RecyclerViewMaterialAdapter(YOUR_RECYCLERVIEW_ADAPTER)"
and at the end dnt forget to Register it
"MaterialViewPagerHelper.registerRecyclerView(mActivity, mList, null);"

**Comment by TheLester** [comment]
thanks it works,didnt see that at first time

**Comment by florent37** [comment]
thanks @omidheshmatinia :+1:
