### ISSUE TITLE
Tab text color is black

### ISSUE THREAD

**Issue by gzuzboey** [florent37/MaterialViewPager#45]
How do i change the tab text color? Because currently the tab text color is black and i cannot really see it.

**Comment by Hzawa** [comment]
Someone correct me if I'm wrong but I believe the text color is pulled from textColorPrimary, in your styles.xml. Try changing that to whatever color you need. Alternatively you can use the custom tab indicator option that's documented in the README.

**Comment by gzuzboey** [comment]
Alright, thanks for the answer I will try that as soon as I can and let u know what happens :)

**Comment by zboing** [comment]
This is not a good approach because the color of the settings and popup overflow menu items will be white color text to white elements (not visible to the user).
A proper use case will be to leave the option from styles.xml unchanged
`<item name="android:textColorPrimary">@android:color/black</item>`
and add the line
`    app:pstsTabTextColor="@android:color/white"`
to com.astuetz.PagerSlidingTabStrip component from material_view_pager_pagertitlestrip_newstand.xml
