### ISSUE TITLE
how to make drawerlayout behide toolbar?

### ISSUE THREAD

**Issue by ares89** [florent37/MaterialViewPager#49]
I found that 
if I want make drawerlayout behide toolbar,
i must change the layout for MaterialViewPager.

could you please add a custom option for making drawerlayout behide toolbar?

thank you

**Comment by florent37** [comment]
to enable the drawerlayout behind the toolbar, those 2 views must be on the same layout. For example drawerlayout must be declared layout_below the toolbar.
I don't think it's possible with MaterialViewPager because the toolbar is declared directly on the header of the MaterialViewPager...

A possible trick is if you set a margin top of the drawerlayout with the height of the toolbar. It's not really a good practice, but I don't know how you can without that

**Comment by ares89** [comment]
thanks~
